# MIT License
# Copyright (c) 2025 Toni Liesche
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

services:
  faas:
    image: tliesche/function-as-a-service:develop
    hostname: faas
    ports:
      - "8080:8080"
    environment:
      - CLOUD_TOOLBOX_COMPONENT_ID=hello-world-faas
      - FUNCTION_AS_A_SERVICE_COMMAND=/usr/local/bin/hello-world-faas
      - FUNCTION_AS_A_SERVICE_PARALLEL_EXECUTION=2
      - FUNCTION_AS_A_SERVICE_EXECUTION_TIMEOUT=10
      - LOG_DEV_MODE=true
      - LOG_LEVEL=trace
      - LOG_PATH=/dev/stdout

  redis:
    image: redis:8.0-M04-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  scylla:
    image: scylladb/scylla
    hostname: scylla
    ports:
      - "9042:9042"
      - "8000:8000"
    command: ["--alternator-address", "0.0.0.0", "--alternator-port", "8000", "--alternator-write-isolation", "always"]
    volumes:
      - scylla_data:/var/lib/scylla

volumes:
  redis_data:
    driver: local
  scylla_data:
    driver: local
