# MIT License
# Copyright (c) 2025 Toni Liesche
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

services:
  ep:
    image: tliesche/event-publisher:develop
    hostname: ${EP_HOSTNAME}
    ports:
      - "${EP_HOST_PORT}:${EP_PORT}"
    environment:
      - CLOUD_TOOLBOX_COMPONENT_ID=ep-${EP_FUNCTION}
      - EVENT_PUBLISHER_PUBLISHER_NAME=${FAAS_FUNCTION}
      - EVENT_PUBLISHER_BACKEND=rabbitmq
      - RABBITMQ_PUBLISHER_VHOST=${FT_RABBITMQ_VHOST}
      - RABBITMQ_PUBLISHER_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PUBLISHER_PORT=${RABBITMQ_PORT}
      - RABBITMQ_PUBLISHER_USERNAME=${EP_RABBITMQ_USER}
      - RABBITMQ_PUBLISHER_PASSWORD=${EP_RABBITMQ_PASSWORD}
      - RABBITMQ_EXCHANGES=trigger=${FT_RABBITMQ_EXCHANGE}
      - LOG_DEV_MODE=${LOG_DEV_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=/dev/stdout

  faas:
    image: tliesche/function-as-a-service:develop
    hostname: ${FAAS_HOSTNAME}
    ports:
      - "${FAAS_HOST_PORT}:${FAAS_PORT}"
    environment:
      - CLOUD_TOOLBOX_COMPONENT_ID=faas-${FAAS_FUNCTION}
      - FUNCTION_AS_A_SERVICE_FUNCTION_NAME=${FAAS_FUNCTION}
      - FUNCTION_AS_A_SERVICE_COMMAND=/usr/local/bin/hello-world-faas
      - FUNCTION_AS_A_SERVICE_PARALLEL_EXECUTION_LIMIT=${FAAS_PARALLEL_EXECUTION_LIMIT}
      - FUNCTION_AS_A_SERVICE_EXECUTION_TIMEOUT=${FAAS_EXECUTION_TIMEOUT}
      - FUNCTION_AS_A_SERVICE_STORAGE_BACKEND=${FAAS_STORAGE_BACKEND}
      - FUNCTION_AS_A_SERVICE_STORAGE_TTL=${FAAS_STORAGE_TTL}
      - SCYLLA_USERNAME=${FAAS_STORAGE_USERNAME}
      - SCYLLA_PASSWORD=${FAAS_STORAGE_PASSWORD}
      - SCYLLA_HOST=${SCYLLA_HOST}
      - SCYLLA_TABLE=${FAAS_STORAGE_TABLE_SCYLLA}
      - SCYLLA_PORT=${SCYLLA_PORT}
      - SCYLLA_REGION=${SCYLLA_REGION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOG_DEV_MODE=${LOG_DEV_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=/dev/stdout

  ft:
    image: tliesche/function-trigger:develop
    hostname: ft
    environment:
      - CLOUD_TOOLBOX_COMPONENT_ID=ft-${FAAS_FUNCTION}
      - FUNCTION_TRIGGER_TRIGGER_NAME=rmq-${FAAS_FUNCTION}
      - FUNCTION_TRIGGER_BATCH_SIZE=${FT_BATCH_SIZE}
      - FUNCTION_TRIGGER_BATCH_TIMEOUT=${FT_BATCH_TIMEOUT}
      - FUNCTION_TRIGGER_PARALLEL_EXECUTION_LIMIT=${FAAS_PARALLEL_EXECUTION_LIMIT}
      - FUNCTION_TRIGGER_SOURCE=rabbitmq
      - FUNCTION_TRIGGER_FAAS_HOST=${FAAS_HOSTNAME}
      - FUNCTION_TRIGGER_FAAS_PORT=${FAAS_PORT}
      - FUNCTION_TRIGGER_FAAS_FUNCTION_NAME=${FAAS_FUNCTION}
      - FUNCTION_TRIGGER_FAAS_TIMEOUT=${FAAS_EXECUTION_TIMEOUT}
      - RABBITMQ_CONSUMER_VHOST=${FT_RABBITMQ_VHOST}
      - RABBITMQ_CONSUMER_HOST=${RABBITMQ_HOST}
      - RABBITMQ_CONSUMER_PORT=${RABBITMQ_PORT}
      - RABBITMQ_CONSUMER_USERNAME=${FT_RABBITMQ_USER}
      - RABBITMQ_CONSUMER_PASSWORD=${FT_RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUES=trigger=${FT_RABBITMQ_QUEUE}
      - LOG_DEV_MODE=${LOG_DEV_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=/dev/stdout

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:8.0-M04-alpine
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:2.66
    hostname: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:5.1.3
    hostname: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://${SCYLLA_HOST}:${SCYLLA_PORT}
      - AWS_REGION=${SCYLLA_REGION}
      - AWS_ACCESS_KEY_ID=${SCYLLA_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${SCYLLA_SECRET_ACCESS_KEY}
    depends_on:
      - scylla

  scylla:
    image: scylladb/scylla:6.2
    hostname: scylla
    ports:
      - "9042:9042"
      - "${SCYLLA_PORT}:${SCYLLA_PORT}"
    command: [
            "--alternator-address", "0.0.0.0",
            "--alternator-ttl-period-in-seconds ", "5",
            "--alternator-port", "${SCYLLA_PORT}",
            "--alternator-write-isolation",
            "always"
        ]
    volumes:
      - scylla_data:/var/lib/scylla

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
  scylla_data:
    driver: local
